### ISSUE TITLE
移動可否判定をどうするか考える

### ISSUE THREAD

**Issue by gforestshade** [TatemonSugorokuGame/TatemonSugorokuGame#11]
移動入力中の段階で、移動不可なマスは動的に変化する。
Model側に判定関数をつくってもらうか？　Presenterで吸収するか？

**Comment by AkioMabuchi** [comment]
桃鉄のように、入力した方向と正反対のキーを押せばキャンセルできるようにしたい。

また、全パターンでも動けない場合の判定関数をModel側で作成し、PlayerIDと移動量の2変数を引数とするbool型のメソッドを実装し、移動可能ならばtrue、移動不可ならばfalseを返す。

サイコロの目が確定した後、このメソッドを呼び出したい。

**Comment by gforestshade** [comment]
移動関連のイメージです
移動中にルートをどう取ってるかはUI表示にかなり食い込むので、
いったんこういうイメージを持ってます

// 【移動前】
// プレイヤーがある出目を出したとき、詰んでいないか
//
// 引数：
//   playerId: 移動しようとしているプレイヤーのID
//   numberOfDice: 出目
//
// 戻り値：
//   出目の数だけ移動できるならtrue, どうやっても無理ならfalse
public int CanMove(int playerId, int numberOfDice)


// 【移動中】
// プレイヤーがあるルートで移動してきたとき、
// 次に4方向のうちどちらに移動できるか
// 敵たてもん、壁、戻り方向などには移動できない
//
// 引数：
//   playerId: 移動したプレイヤーのID
//   verts: 通ってきた頂点番号のリスト(通った順に)(1次元配列にならした0-63の番号を使う)
//
// 戻り値：
//   移動できる方向のビット和
//      1: ↑
//      2: →
//      4: ↓
//      8: ←
public int CanMoveDir(int playerId, IList<int> verts)

// 【移動完了】
// プレイヤーの移動によって塗りかえしを実行し、次のターンに進む
// 引数：
//   playerId: 移動したプレイヤーのID
//   verts: 通った頂点番号のリスト(通った順に)(1次元配列にならした0-63の番号を使う)
// 戻り値：
//  scores: 各プレイヤーの点数
// (後で別の関数から取得する形でもよい)
public List<int> Paint(int playerId, IList<int> verts )
