### ISSUE TITLE
タイルの状態の変更をどう扱うか考える

### ISSUE THREAD

**Issue by gforestshade** [TatemonSugorokuGame/TatemonSugorokuGame#12]
リアルタイムで通り道が塗り替わっているように見せるか？
その場合、Viewで必要なデータを全部持つか？　Model側にも手伝ってもらうか？

**Comment by AkioMabuchi** [comment]
私の意見としては、リアルタイムで通り道が塗り変わるように見せたいです。

プレイヤーが1マス移動後に塗り替えたいです。

またプレイヤーが1マス移動後にModelの移動処理メソッドMovePlayer(int playerId, MoveDirection direction)を呼び出し
Model側がその場に応じて得点加算処理などを行うと同時に、int[]型のマスの所有状況のイベント「DomainInformation」を発行します。それをObserveして、View側で描画処理を行なって欲しいです。

MoveDirectionはUp、Right、Down、Leftの値を持つenum型です。

**Comment by gforestshade** [comment]
食い違ってしまいました。
https://uozugame.slack.com/archives/C029D3C481M/p1627894545019200?thread_ts=1627861567.016300&cid=C029D3C481M
調整が必要そうです。

1マス移動ごとにメッセージをやり取りしたいという方針については理解しました。
1マスずつという前提の下では、タイルの状態変更イベントにおいてView側で描画処理を行うのに必要なのは、
・どのマスが
・進んだか戻ったことによって
・前の所有状況から
・今の所有状況に変わった
の情報です。

全マスの所有状況を伝えるのは設計としては奇麗ですが、ほとんどのマスは変化していないことが保証されているうえ、アニメーションを実装することも難しくなってしまうかもしれません。

**Comment by AkioMabuchi** [comment]
なるほど、タイルの色の場合は、実際にView側にもタイルの色の状態を保持するint[]型の配列を用意して、値の変更があった場合のみ更新描画処理を行うのは可能でしょうか？

private int[] _cells = new int[64];

public void DrawCells(int[] cells)
{
    for(int i=0; i<64;i++)
    {
        if(_cells[i]==cells[i]) continue;
        // 描画処理
        _cells[i] = cells[i];
    }
}

変化するマスは1移動につき1マスが保証されている中で、全データを渡すのは確かに計算量的にも悪いですが、
N=64という範囲では問題ないと思います。

プレイヤーの移動につきましても、View側でプレイヤーの位置を保持し、移動と同時に移動のアニメーションも十分可能かと思われますが、いかがでしょうか？

**Comment by gforestshade** [comment]
なるほど、OKです。
企画者さんは一気に塗るとおっしゃっていますが、状態として仮塗り(赤)みたいな値を定義すれば対応は可能だと思います。
そのあたりの値の定義はModel側に都合がいいように決めるのが一番だと思うので、お任せしてよろしいでしょうか？

**Comment by AkioMabuchi** [comment]
はい、大丈夫です。
-1：無所属
0、1：プレイヤー所持。
